apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: rollingUpdate:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PORT
              value: {{ .Values.env.port }}